# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
conda install numpy 


Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [7]:
np.version.version

'1.21.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
A = np.random.rand(2,3,5)
print(A)


[[[0.95319266 0.29670425 0.78138667 0.14718496 0.61770108]
  [0.74032023 0.07570386 0.21740612 0.74016291 0.64176003]
  [0.29943698 0.21591269 0.28059897 0.32245446 0.49739412]]

 [[0.60450011 0.37254651 0.14659301 0.10625039 0.6069402 ]
  [0.61845089 0.11883135 0.38313065 0.27973307 0.84000253]
  [0.3653002  0.42818214 0.87938378 0.47818047 0.66376546]]]


In [13]:
A= np.random.randint(5, size=(2,3,5))
print(A)

[[[2 2 3 4 0]
  [2 1 2 0 0]
  [0 2 1 1 1]]

 [[4 2 2 2 1]
  [0 4 1 3 0]
  [4 1 0 0 1]]]


In [77]:
A=np.random.rand(2,3,5)
print(A)

[[[0.95856774 0.96087724 0.96648907 0.45926907 0.45329858]
  [0.95656004 0.96220884 0.65843688 0.93299772 0.28495049]
  [0.73665896 0.7634428  0.51889668 0.66875606 0.05318205]]

 [[0.39446926 0.48164068 0.4313324  0.42102676 0.01541288]
  [0.09194509 0.91799446 0.66368386 0.59534666 0.45231542]
  [0.2117701  0.06547703 0.49650236 0.65004542 0.63252766]]]


#### 4. Print *a*.


In [78]:
print(A)
print(A.shape)

[[[0.95856774 0.96087724 0.96648907 0.45926907 0.45329858]
  [0.95656004 0.96220884 0.65843688 0.93299772 0.28495049]
  [0.73665896 0.7634428  0.51889668 0.66875606 0.05318205]]

 [[0.39446926 0.48164068 0.4313324  0.42102676 0.01541288]
  [0.09194509 0.91799446 0.66368386 0.59534666 0.45231542]
  [0.2117701  0.06547703 0.49650236 0.65004542 0.63252766]]]
(2, 3, 5)


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [79]:
b = np.ones((5,2,3))
print(b)
b.ndim


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


3

#### 6. Print *b*.


In [80]:
print(b)
print(b.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [81]:
print(np.array_equal(A,b))

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [82]:
c = np.concatenate((A,b))

#WE CANT COMBINE, CAUSE OF THE SHAPES



ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [83]:
c = np.transpose(b,(1,2,0))
print(c)
print(A.shape)
print(b.shape)
print(c.shape)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [87]:


d = A+c
print(d)

print(np.shape(A))
print(np.shape(c))



[[[3.87570321 3.88263171 3.89946722 2.3778072  2.35989574]
  [3.86968012 3.88662651 2.97531065 3.79899316 1.85485146]
  [3.20997689 3.29032841 2.55669003 3.00626818 1.15954614]]

 [[2.18340778 2.44492205 2.29399721 2.26308029 1.04623864]
  [1.27583526 3.75398337 2.99105159 2.78603998 2.35694626]
  [1.63531029 1.19643108 2.48950707 2.95013626 2.89758299]]]
(2, 3, 5)
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [88]:
print(A)
print(d)



[[[0.95856774 0.96087724 0.96648907 0.45926907 0.45329858]
  [0.95656004 0.96220884 0.65843688 0.93299772 0.28495049]
  [0.73665896 0.7634428  0.51889668 0.66875606 0.05318205]]

 [[0.39446926 0.48164068 0.4313324  0.42102676 0.01541288]
  [0.09194509 0.91799446 0.66368386 0.59534666 0.45231542]
  [0.2117701  0.06547703 0.49650236 0.65004542 0.63252766]]]
[[[3.87570321 3.88263171 3.89946722 2.3778072  2.35989574]
  [3.86968012 3.88662651 2.97531065 3.79899316 1.85485146]
  [3.20997689 3.29032841 2.55669003 3.00626818 1.15954614]]

 [[2.18340778 2.44492205 2.29399721 2.26308029 1.04623864]
  [1.27583526 3.75398337 2.99105159 2.78603998 2.35694626]
  [1.63531029 1.19643108 2.48950707 2.95013626 2.89758299]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [95]:

e = A*c
print(e)
print(np.ndim(A))
print(np.ndim(c))


[[[2.79627194 2.80744737 2.83469134 0.88112522 0.86425778]
  [2.78657427 2.81390054 1.52551514 2.67396721 0.44734405]
  [1.82199182 1.92913263 1.0574042  1.5632254  0.05883871]]

 [[0.70568125 0.94559618 0.80342769 0.77555384 0.01588799]
  [0.10885288 2.6034221  1.5446364  1.30422196 0.8614939 ]
  [0.30146325 0.07405151 0.98953154 1.49516351 1.43271015]]]
3
3


#### 13. Does *e* equal to *a*? Why or why not?


In [98]:

print(A)
print(e)



print(np.array_equal(A,e))


[[[0.95856774 0.96087724 0.96648907 0.45926907 0.45329858]
  [0.95656004 0.96220884 0.65843688 0.93299772 0.28495049]
  [0.73665896 0.7634428  0.51889668 0.66875606 0.05318205]]

 [[0.39446926 0.48164068 0.4313324  0.42102676 0.01541288]
  [0.09194509 0.91799446 0.66368386 0.59534666 0.45231542]
  [0.2117701  0.06547703 0.49650236 0.65004542 0.63252766]]]
[[[2.79627194 2.80744737 2.83469134 0.88112522 0.86425778]
  [2.78657427 2.81390054 1.52551514 2.67396721 0.44734405]
  [1.82199182 1.92913263 1.0574042  1.5632254  0.05883871]]

 [[0.70568125 0.94559618 0.80342769 0.77555384 0.01588799]
  [0.10885288 2.6034221  1.5446364  1.30422196 0.8614939 ]
  [0.30146325 0.07405151 0.98953154 1.49516351 1.43271015]]]
False


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [101]:
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

3.899467223866904
1.046238640105
2.6856082255894553


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [107]:
f = np.empty((2,3,5))
print(f)
#EN REALIDAD ESE ARRAY ES EMPTY PERO ME TIENE QUE MOSTRAR ALGO, POR ESO ME PONE NUMEROS ALEATORIOS.

[[[2.79627194 2.80744737 2.83469134 0.88112522 0.86425778]
  [2.78657427 2.81390054 1.52551514 2.67396721 0.44734405]
  [1.82199182 1.92913263 1.0574042  1.5632254  0.05883871]]

 [[0.70568125 0.94559618 0.80342769 0.77555384 0.01588799]
  [0.10885288 2.6034221  1.5446364  1.30422196 0.8614939 ]
  [0.30146325 0.07405151 0.98953154 1.49516351 1.43271015]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

25.0

In [122]:
f =[]
for i in np.nditer(d):
    if i>d_min and i<d_mean:
        f.append(25)
    elif i>d_mean and i <d_max:
        f.append(75)
    elif i == d_mean:
        f.append(50)
    elif i == d_min:
        f.append(0)
    elif i== d_max:
        f.append(100)
f = np.reshape(f,(2,3,5))
print(f)



[[[ 75  75 100  25  25]
  [ 75  75  75  75  25]
  [ 75  75  25  75  25]]

 [[ 25  25  25  25   0]
  [ 25  75  75  75  25]
  [ 25  25  25  75  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [123]:
print(d)
print(f)

[[[3.87570321 3.88263171 3.89946722 2.3778072  2.35989574]
  [3.86968012 3.88662651 2.97531065 3.79899316 1.85485146]
  [3.20997689 3.29032841 2.55669003 3.00626818 1.15954614]]

 [[2.18340778 2.44492205 2.29399721 2.26308029 1.04623864]
  [1.27583526 3.75398337 2.99105159 2.78603998 2.35694626]
  [1.63531029 1.19643108 2.48950707 2.95013626 2.89758299]]]
[[[ 75  75 100  25  25]
  [ 75  75  75  75  25]
  [ 75  75  25  75  25]]

 [[ 25  25  25  25   0]
  [ 25  75  75  75  25]
  [ 25  25  25  75  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here